/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package concertdb;

/**
 *
 * @author Kohner Smith
 */
public class HostMainPage extends javax.swing.JInternalFrame {

    /**
     * Creates new form UserMainPage
     */
    public HostMainPage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jPanel9 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        BackGroundPanel = new javax.swing.JPanel();
        OverviewTabbedPane = new javax.swing.JTabbedPane();
        DashboardBackgroundPanel = new javax.swing.JPanel();
        DashboardWelcomeLabel = new javax.swing.JLabel();
        DashboardUpcomingPanel = new javax.swing.JPanel();
        DashboardRecentlyChangedPanel = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        CreationCenterTabsTabbedPane = new javax.swing.JTabbedPane();
        VenueBackgroundPanel = new javax.swing.JPanel();
        VenueBackgroundPanel2 = new javax.swing.JPanel();
        HeaderVenue = new javax.swing.JLabel();
        VenueNameLabel = new javax.swing.JLabel();
        VenueNameTextfield = new javax.swing.JTextField();
        VenueIDLabel = new javax.swing.JLabel();
        VenueAddressTextfield = new javax.swing.JTextField();
        VenueIDTextfield = new javax.swing.JTextField();
        VenueCreateButton = new javax.swing.JButton();
        VenueAddressLabel = new javax.swing.JLabel();
        ArtistBackgroundPanel = new javax.swing.JPanel();
        ArtistBackgroundPanel2 = new javax.swing.JPanel();
        HeaderArtist = new javax.swing.JLabel();
        ArtistCreateButton = new javax.swing.JButton();
        ArtistNameLabel = new javax.swing.JLabel();
        ArtistNameTextfield = new javax.swing.JTextField();
        ArtistGenreLabel = new javax.swing.JLabel();
        ArtistGenreTextfield = new javax.swing.JTextField();
        ConcertBackgroundPanel = new javax.swing.JPanel();
        HeaderConcert = new javax.swing.JLabel();
        ConcertCreateButton = new javax.swing.JButton();
        ConcertNameLabel = new javax.swing.JLabel();
        ConcertNameTextfield = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        ConcertVenueLabel = new javax.swing.JLabel();
        ConcertArtistLabel = new javax.swing.JLabel();
        VenueSelectionComboBox = new javax.swing.JComboBox<>();
        ArtistSelectionComboBox = new javax.swing.JComboBox<>();
        ConcertPriceTextfield = new javax.swing.JTextField();
        ConcertDateTextfield = new javax.swing.JTextField();

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jList1);

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 403, Short.MAX_VALUE)
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 306, Short.MAX_VALUE)
        );

        jPanel10.setBackground(new java.awt.Color(222, 222, 222));
        jPanel10.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Upcoming!", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 3, 14))); // NOI18N
        jPanel10.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 340, Short.MAX_VALUE)
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 270, Short.MAX_VALUE)
        );

        jPanel11.setBackground(new java.awt.Color(222, 222, 222));
        jPanel11.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Upcoming!", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 3, 14))); // NOI18N
        jPanel11.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 340, Short.MAX_VALUE)
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 270, Short.MAX_VALUE)
        );

        setBackground(new java.awt.Color(92, 64, 51));

        BackGroundPanel.setBackground(new java.awt.Color(92, 64, 51));

        OverviewTabbedPane.setBackground(new java.awt.Color(255, 222, 89));
        OverviewTabbedPane.setForeground(new java.awt.Color(92, 64, 51));
        OverviewTabbedPane.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N

        DashboardBackgroundPanel.setBackground(new java.awt.Color(255, 222, 89));

        DashboardWelcomeLabel.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        DashboardWelcomeLabel.setForeground(new java.awt.Color(92, 64, 51));
        DashboardWelcomeLabel.setText("Welcome!");

        DashboardUpcomingPanel.setBackground(new java.awt.Color(92, 64, 51));
        DashboardUpcomingPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Upcoming!", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 3, 14), new java.awt.Color(255, 222, 89))); // NOI18N
        DashboardUpcomingPanel.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N

        javax.swing.GroupLayout DashboardUpcomingPanelLayout = new javax.swing.GroupLayout(DashboardUpcomingPanel);
        DashboardUpcomingPanel.setLayout(DashboardUpcomingPanelLayout);
        DashboardUpcomingPanelLayout.setHorizontalGroup(
            DashboardUpcomingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 370, Short.MAX_VALUE)
        );
        DashboardUpcomingPanelLayout.setVerticalGroup(
            DashboardUpcomingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        DashboardRecentlyChangedPanel.setBackground(new java.awt.Color(92, 64, 51));
        DashboardRecentlyChangedPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Recently Changed/Made!", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 3, 14), new java.awt.Color(255, 222, 89))); // NOI18N
        DashboardRecentlyChangedPanel.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N

        javax.swing.GroupLayout DashboardRecentlyChangedPanelLayout = new javax.swing.GroupLayout(DashboardRecentlyChangedPanel);
        DashboardRecentlyChangedPanel.setLayout(DashboardRecentlyChangedPanelLayout);
        DashboardRecentlyChangedPanelLayout.setHorizontalGroup(
            DashboardRecentlyChangedPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 376, Short.MAX_VALUE)
        );
        DashboardRecentlyChangedPanelLayout.setVerticalGroup(
            DashboardRecentlyChangedPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 263, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout DashboardBackgroundPanelLayout = new javax.swing.GroupLayout(DashboardBackgroundPanel);
        DashboardBackgroundPanel.setLayout(DashboardBackgroundPanelLayout);
        DashboardBackgroundPanelLayout.setHorizontalGroup(
            DashboardBackgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DashboardBackgroundPanelLayout.createSequentialGroup()
                .addComponent(DashboardUpcomingPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 152, Short.MAX_VALUE)
                .addComponent(DashboardRecentlyChangedPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(DashboardBackgroundPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(DashboardWelcomeLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        DashboardBackgroundPanelLayout.setVerticalGroup(
            DashboardBackgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DashboardBackgroundPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(DashboardWelcomeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(DashboardBackgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(DashboardRecentlyChangedPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(DashboardUpcomingPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18))
        );

        OverviewTabbedPane.addTab("Dashboard", DashboardBackgroundPanel);

        jPanel2.setBackground(new java.awt.Color(92, 64, 51));

        CreationCenterTabsTabbedPane.setBackground(new java.awt.Color(255, 222, 89));
        CreationCenterTabsTabbedPane.setForeground(new java.awt.Color(92, 64, 51));
        CreationCenterTabsTabbedPane.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N

        VenueBackgroundPanel.setBackground(new java.awt.Color(255, 222, 50));

        VenueBackgroundPanel2.setBackground(new java.awt.Color(255, 222, 89));

        HeaderVenue.setBackground(new java.awt.Color(255, 222, 89));
        HeaderVenue.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        HeaderVenue.setForeground(new java.awt.Color(92, 64, 51));
        HeaderVenue.setText("Please Enter the Information Below");

        VenueNameLabel.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        VenueNameLabel.setForeground(new java.awt.Color(92, 64, 51));
        VenueNameLabel.setText("Name");

        VenueNameTextfield.setBackground(new java.awt.Color(92, 64, 51));
        VenueNameTextfield.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        VenueNameTextfield.setForeground(new java.awt.Color(255, 222, 89));
        VenueNameTextfield.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        VenueIDLabel.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        VenueIDLabel.setForeground(new java.awt.Color(92, 64, 51));
        VenueIDLabel.setText("ID");

        VenueAddressTextfield.setBackground(new java.awt.Color(92, 64, 51));
        VenueAddressTextfield.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        VenueAddressTextfield.setForeground(new java.awt.Color(255, 222, 89));
        VenueAddressTextfield.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        VenueIDTextfield.setBackground(new java.awt.Color(92, 64, 51));
        VenueIDTextfield.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        VenueIDTextfield.setForeground(new java.awt.Color(255, 222, 89));
        VenueIDTextfield.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        VenueIDTextfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VenueIDTextfieldActionPerformed(evt);
            }
        });

        VenueCreateButton.setBackground(new java.awt.Color(92, 64, 51));
        VenueCreateButton.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        VenueCreateButton.setForeground(new java.awt.Color(255, 222, 89));
        VenueCreateButton.setText("Create!");
        VenueCreateButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        VenueCreateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VenueCreateButtonActionPerformed(evt);
            }
        });

        VenueAddressLabel.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        VenueAddressLabel.setForeground(new java.awt.Color(92, 64, 51));
        VenueAddressLabel.setText("Address");

        javax.swing.GroupLayout VenueBackgroundPanel2Layout = new javax.swing.GroupLayout(VenueBackgroundPanel2);
        VenueBackgroundPanel2.setLayout(VenueBackgroundPanel2Layout);
        VenueBackgroundPanel2Layout.setHorizontalGroup(
            VenueBackgroundPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(VenueBackgroundPanel2Layout.createSequentialGroup()
                .addComponent(HeaderVenue)
                .addGap(0, 519, Short.MAX_VALUE))
            .addGroup(VenueBackgroundPanel2Layout.createSequentialGroup()
                .addGroup(VenueBackgroundPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(VenueBackgroundPanel2Layout.createSequentialGroup()
                        .addGroup(VenueBackgroundPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(VenueBackgroundPanel2Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addGroup(VenueBackgroundPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(VenueNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(VenueBackgroundPanel2Layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addComponent(VenueIDLabel))))
                            .addComponent(VenueAddressLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(VenueBackgroundPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(VenueIDTextfield, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(VenueNameTextfield, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(VenueAddressTextfield, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 307, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, VenueBackgroundPanel2Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(VenueCreateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        VenueBackgroundPanel2Layout.setVerticalGroup(
            VenueBackgroundPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(VenueBackgroundPanel2Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(HeaderVenue, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23)
                .addGroup(VenueBackgroundPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(VenueNameTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(VenueNameLabel))
                .addGap(18, 18, 18)
                .addGroup(VenueBackgroundPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(VenueIDLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(VenueIDTextfield))
                .addGap(18, 18, 18)
                .addGroup(VenueBackgroundPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(VenueAddressTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(VenueAddressLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 116, Short.MAX_VALUE)
                .addComponent(VenueCreateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout VenueBackgroundPanelLayout = new javax.swing.GroupLayout(VenueBackgroundPanel);
        VenueBackgroundPanel.setLayout(VenueBackgroundPanelLayout);
        VenueBackgroundPanelLayout.setHorizontalGroup(
            VenueBackgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(VenueBackgroundPanelLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(VenueBackgroundPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        VenueBackgroundPanelLayout.setVerticalGroup(
            VenueBackgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(VenueBackgroundPanelLayout.createSequentialGroup()
                .addComponent(VenueBackgroundPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        CreationCenterTabsTabbedPane.addTab("Venue", VenueBackgroundPanel);

        ArtistBackgroundPanel.setBackground(new java.awt.Color(255, 222, 89));

        ArtistBackgroundPanel2.setBackground(new java.awt.Color(255, 222, 89));

        HeaderArtist.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        HeaderArtist.setForeground(new java.awt.Color(92, 64, 51));
        HeaderArtist.setText("Please Enter the Information Below!");

        ArtistCreateButton.setBackground(new java.awt.Color(92, 64, 51));
        ArtistCreateButton.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        ArtistCreateButton.setForeground(new java.awt.Color(255, 222, 89));
        ArtistCreateButton.setText("Create!");
        ArtistCreateButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        ArtistNameLabel.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        ArtistNameLabel.setForeground(new java.awt.Color(92, 64, 51));
        ArtistNameLabel.setText("Name");

        ArtistNameTextfield.setBackground(new java.awt.Color(92, 64, 51));
        ArtistNameTextfield.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        ArtistNameTextfield.setForeground(new java.awt.Color(255, 222, 89));
        ArtistNameTextfield.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        ArtistGenreLabel.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        ArtistGenreLabel.setForeground(new java.awt.Color(92, 64, 51));
        ArtistGenreLabel.setText("Genre");

        ArtistGenreTextfield.setBackground(new java.awt.Color(92, 64, 51));
        ArtistGenreTextfield.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        ArtistGenreTextfield.setForeground(new java.awt.Color(255, 222, 89));
        ArtistGenreTextfield.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        javax.swing.GroupLayout ArtistBackgroundPanel2Layout = new javax.swing.GroupLayout(ArtistBackgroundPanel2);
        ArtistBackgroundPanel2.setLayout(ArtistBackgroundPanel2Layout);
        ArtistBackgroundPanel2Layout.setHorizontalGroup(
            ArtistBackgroundPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ArtistBackgroundPanel2Layout.createSequentialGroup()
                .addComponent(HeaderArtist)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(ArtistBackgroundPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ArtistBackgroundPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ArtistBackgroundPanel2Layout.createSequentialGroup()
                        .addComponent(ArtistGenreLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ArtistGenreTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(ArtistBackgroundPanel2Layout.createSequentialGroup()
                        .addComponent(ArtistNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ArtistNameTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(492, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ArtistBackgroundPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(ArtistCreateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        ArtistBackgroundPanel2Layout.setVerticalGroup(
            ArtistBackgroundPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ArtistBackgroundPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(HeaderArtist, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(ArtistBackgroundPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ArtistNameTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ArtistNameLabel))
                .addGap(18, 18, 18)
                .addGroup(ArtistBackgroundPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ArtistGenreLabel)
                    .addComponent(ArtistGenreTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 183, Short.MAX_VALUE)
                .addComponent(ArtistCreateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout ArtistBackgroundPanelLayout = new javax.swing.GroupLayout(ArtistBackgroundPanel);
        ArtistBackgroundPanel.setLayout(ArtistBackgroundPanelLayout);
        ArtistBackgroundPanelLayout.setHorizontalGroup(
            ArtistBackgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(ArtistBackgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(ArtistBackgroundPanelLayout.createSequentialGroup()
                    .addGap(0, 70, Short.MAX_VALUE)
                    .addComponent(ArtistBackgroundPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 71, Short.MAX_VALUE)))
        );
        ArtistBackgroundPanelLayout.setVerticalGroup(
            ArtistBackgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(ArtistBackgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(ArtistBackgroundPanelLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(ArtistBackgroundPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        CreationCenterTabsTabbedPane.addTab("Artist", ArtistBackgroundPanel);

        ConcertBackgroundPanel.setBackground(new java.awt.Color(255, 222, 89));

        HeaderConcert.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        HeaderConcert.setForeground(new java.awt.Color(92, 64, 51));
        HeaderConcert.setText("Please Enter the Information Below");

        ConcertCreateButton.setBackground(new java.awt.Color(92, 64, 51));
        ConcertCreateButton.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        ConcertCreateButton.setForeground(new java.awt.Color(255, 222, 89));
        ConcertCreateButton.setText("Create!");
        ConcertCreateButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        ConcertCreateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConcertCreateButtonActionPerformed(evt);
            }
        });

        ConcertNameLabel.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        ConcertNameLabel.setForeground(new java.awt.Color(92, 64, 51));
        ConcertNameLabel.setText("Name");

        ConcertNameTextfield.setBackground(new java.awt.Color(92, 64, 51));
        ConcertNameTextfield.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        ConcertNameTextfield.setForeground(new java.awt.Color(255, 222, 89));
        ConcertNameTextfield.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(92, 64, 51));
        jLabel3.setText("Date");

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(92, 64, 51));
        jLabel4.setText("Price");

        ConcertVenueLabel.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        ConcertVenueLabel.setForeground(new java.awt.Color(92, 64, 51));
        ConcertVenueLabel.setText("Venue");

        ConcertArtistLabel.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        ConcertArtistLabel.setForeground(new java.awt.Color(92, 64, 51));
        ConcertArtistLabel.setText("Artist");

        VenueSelectionComboBox.setBackground(new java.awt.Color(92, 64, 51));
        VenueSelectionComboBox.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        VenueSelectionComboBox.setForeground(new java.awt.Color(255, 222, 89));
        VenueSelectionComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        VenueSelectionComboBox.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        ArtistSelectionComboBox.setBackground(new java.awt.Color(92, 64, 51));
        ArtistSelectionComboBox.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        ArtistSelectionComboBox.setForeground(new java.awt.Color(255, 222, 89));
        ArtistSelectionComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        ArtistSelectionComboBox.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        ConcertPriceTextfield.setBackground(new java.awt.Color(92, 64, 51));
        ConcertPriceTextfield.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        ConcertPriceTextfield.setForeground(new java.awt.Color(255, 222, 89));
        ConcertPriceTextfield.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        ConcertDateTextfield.setBackground(new java.awt.Color(92, 64, 51));
        ConcertDateTextfield.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        ConcertDateTextfield.setForeground(new java.awt.Color(255, 222, 89));
        ConcertDateTextfield.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        javax.swing.GroupLayout ConcertBackgroundPanelLayout = new javax.swing.GroupLayout(ConcertBackgroundPanel);
        ConcertBackgroundPanel.setLayout(ConcertBackgroundPanelLayout);
        ConcertBackgroundPanelLayout.setHorizontalGroup(
            ConcertBackgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ConcertBackgroundPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ConcertBackgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ConcertBackgroundPanelLayout.createSequentialGroup()
                        .addGroup(ConcertBackgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(ConcertNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(ConcertBackgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(ConcertNameTextfield, javax.swing.GroupLayout.DEFAULT_SIZE, 218, Short.MAX_VALUE)
                            .addComponent(ConcertDateTextfield))
                        .addGap(18, 18, 18)
                        .addComponent(ConcertVenueLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(VenueSelectionComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(ConcertArtistLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ArtistSelectionComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 144, Short.MAX_VALUE))
                    .addGroup(ConcertBackgroundPanelLayout.createSequentialGroup()
                        .addGroup(ConcertBackgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(ConcertBackgroundPanelLayout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ConcertPriceTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(HeaderConcert))
                        .addContainerGap(639, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ConcertBackgroundPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ConcertCreateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );
        ConcertBackgroundPanelLayout.setVerticalGroup(
            ConcertBackgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ConcertBackgroundPanelLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(HeaderConcert, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(ConcertBackgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ConcertNameTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(ConcertBackgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(ConcertArtistLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(ConcertVenueLabel)
                        .addComponent(VenueSelectionComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(ArtistSelectionComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(ConcertNameLabel)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ConcertBackgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ConcertDateTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(10, 10, 10)
                .addGroup(ConcertBackgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(ConcertPriceTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 157, Short.MAX_VALUE)
                .addComponent(ConcertCreateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        CreationCenterTabsTabbedPane.addTab("Concert", ConcertBackgroundPanel);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(CreationCenterTabsTabbedPane)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(CreationCenterTabsTabbedPane, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        OverviewTabbedPane.addTab("Creation Center", jPanel2);

        javax.swing.GroupLayout BackGroundPanelLayout = new javax.swing.GroupLayout(BackGroundPanel);
        BackGroundPanel.setLayout(BackGroundPanelLayout);
        BackGroundPanelLayout.setHorizontalGroup(
            BackGroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(OverviewTabbedPane)
        );
        BackGroundPanelLayout.setVerticalGroup(
            BackGroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BackGroundPanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(OverviewTabbedPane, javax.swing.GroupLayout.PREFERRED_SIZE, 410, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(BackGroundPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(BackGroundPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void VenueCreateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VenueCreateButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_VenueCreateButtonActionPerformed

    private void VenueIDTextfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VenueIDTextfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_VenueIDTextfieldActionPerformed

    private void ConcertCreateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConcertCreateButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ConcertCreateButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel ArtistBackgroundPanel;
    private javax.swing.JPanel ArtistBackgroundPanel2;
    private javax.swing.JButton ArtistCreateButton;
    private javax.swing.JLabel ArtistGenreLabel;
    private javax.swing.JTextField ArtistGenreTextfield;
    private javax.swing.JLabel ArtistNameLabel;
    private javax.swing.JTextField ArtistNameTextfield;
    private javax.swing.JComboBox<String> ArtistSelectionComboBox;
    private javax.swing.JPanel BackGroundPanel;
    private javax.swing.JLabel ConcertArtistLabel;
    private javax.swing.JPanel ConcertBackgroundPanel;
    private javax.swing.JButton ConcertCreateButton;
    private javax.swing.JTextField ConcertDateTextfield;
    private javax.swing.JLabel ConcertNameLabel;
    private javax.swing.JTextField ConcertNameTextfield;
    private javax.swing.JTextField ConcertPriceTextfield;
    private javax.swing.JLabel ConcertVenueLabel;
    private javax.swing.JTabbedPane CreationCenterTabsTabbedPane;
    private javax.swing.JPanel DashboardBackgroundPanel;
    private javax.swing.JPanel DashboardRecentlyChangedPanel;
    private javax.swing.JPanel DashboardUpcomingPanel;
    private javax.swing.JLabel DashboardWelcomeLabel;
    private javax.swing.JLabel HeaderArtist;
    private javax.swing.JLabel HeaderConcert;
    private javax.swing.JLabel HeaderVenue;
    private javax.swing.JTabbedPane OverviewTabbedPane;
    private javax.swing.JLabel VenueAddressLabel;
    private javax.swing.JTextField VenueAddressTextfield;
    private javax.swing.JPanel VenueBackgroundPanel;
    private javax.swing.JPanel VenueBackgroundPanel2;
    private javax.swing.JButton VenueCreateButton;
    private javax.swing.JLabel VenueIDLabel;
    private javax.swing.JTextField VenueIDTextfield;
    private javax.swing.JLabel VenueNameLabel;
    private javax.swing.JTextField VenueNameTextfield;
    private javax.swing.JComboBox<String> VenueSelectionComboBox;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JList<String> jList1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
