/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package concertdb;

import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.List;
import java.util.Random;

import javax.swing.ComboBoxModel;
import javax.swing.DefaultComboBoxModel;
import javax.swing.GroupLayout;
import javax.swing.GroupLayout.Alignment;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.LayoutStyle.ComponentPlacement;
import javax.swing.table.DefaultTableModel;

import bo.Artist;
import bo.Concert;
import bo.Venue;
import dao.ArtistHandler;
import dao.ConcertHandler;
import dao.SeatHandler;
import dao.SectionHandler;
import dao.VenueHandler;
import java.awt.Font;

/**
 *
 * @author Kohner Smith
 */
public class HostMainPage extends BaseWindow {

	/**
	 * Creates new form UserMainPage
	 */
	int counter = 0;

	private void populateVenue() {
		List<Venue> venues = new VenueHandler().getVenues();
		ComboBoxModel ModelComboBox = new DefaultComboBoxModel(venues.toArray());
		VenueSelectionComboBox.setModel(ModelComboBox);

	}

	private void populateArtist() {
		List<Artist> artists = new ArtistHandler().getArtist();
		ComboBoxModel ModelComboBox = new DefaultComboBoxModel(artists.toArray());
		ArtistSelectionComboBox.setModel(ModelComboBox);
	}

	public HostMainPage(BaseWindow lw) {
		this.lastWindow = lw;
		initComponents();
		populateVenue();
		populateConcert();
		populateArtist();
		this.setTitle("Venue Host Main Page");
		this.setVisible(true);
		closePrevious();
	}

	private void populateConcert() {
		List<Concert> concerts = new ConcertHandler().getConcerts();
		String columns[] = new String[] { "Name", "Date", "Price", "Venue ID", "Artist ID" };
		DefaultTableModel tblModel = new DefaultTableModel(columns, 0) {
			@Override
			public boolean isCellEditable(int row, int column) {
				return false;
			}

		};
		concerts.forEach((name) -> {
			tblModel.addRow(name.getRow());
		});
		UpcomingConcerts.setModel(tblModel);
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated
	// Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		jScrollPane1 = new javax.swing.JScrollPane();
		jList1 = new javax.swing.JList<>();
		jPanel9 = new javax.swing.JPanel();
		jPanel10 = new javax.swing.JPanel();
		jPanel11 = new javax.swing.JPanel();
		VenueNameLabel1 = new javax.swing.JLabel();
		jScrollPane2 = new javax.swing.JScrollPane();
		jTable1 = new javax.swing.JTable();
		jScrollPane3 = new javax.swing.JScrollPane();
		jTable2 = new javax.swing.JTable();
		BackGroundPanel = new javax.swing.JPanel();
		OverviewTabbedPane = new javax.swing.JTabbedPane();
		DashboardBackgroundPanel = new javax.swing.JPanel();
		DashboardWelcomeLabel = new javax.swing.JLabel();
		DashboardUpcomingPanel = new javax.swing.JPanel();
		jScrollPane4 = new javax.swing.JScrollPane();
		UpcomingConcerts = new javax.swing.JTable();
		DashboardRefreshButton = new javax.swing.JButton();
		jPanel2 = new javax.swing.JPanel();
		CreationCenterTabsTabbedPane = new javax.swing.JTabbedPane();
		VenueBackgroundPanel = new javax.swing.JPanel();
		VenueBackgroundPanel2 = new javax.swing.JPanel();
		HeaderVenue = new javax.swing.JLabel();
		numberofSectionsLabel = new javax.swing.JLabel();
		VenueIDTextfield = new javax.swing.JTextField();
		SeatsperSectionTextfield = new javax.swing.JTextField();
		VenueCreateButton = new javax.swing.JButton();
		VenueAddressLabel = new javax.swing.JLabel();
		VenueIDLabel = new javax.swing.JLabel();
		numberofSeatsLabel = new javax.swing.JLabel();
		numberofSectionsTextfield = new javax.swing.JTextField();
		VenueAddressTextfield = new javax.swing.JTextField();
		VenueNameLabel = new javax.swing.JLabel();
		VenueNameTextfield = new javax.swing.JTextField();
		ConcertBackgroundPanel = new javax.swing.JPanel();
		HeaderConcert = new javax.swing.JLabel();
		ConcertCreateButton = new javax.swing.JButton();
		ConcertNameLabel = new javax.swing.JLabel();
		ConcertNameTextfield = new javax.swing.JTextField();
		jLabel3 = new javax.swing.JLabel();
		jLabel4 = new javax.swing.JLabel();
		ConcertVenueLabel = new javax.swing.JLabel();
		ConcertArtistLabel = new javax.swing.JLabel();
		VenueSelectionComboBox = new javax.swing.JComboBox<>();
		ArtistSelectionComboBox = new javax.swing.JComboBox<>();
		ConcertPriceTextfield = new javax.swing.JTextField();
		ConcertDateTextfield = new javax.swing.JTextField();
		CreationRefreshButton = new javax.swing.JButton();

		jList1.setModel(new javax.swing.AbstractListModel<String>() {
			String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };

			public int getSize() {
				return strings.length;
			}

			public String getElementAt(int i) {
				return strings[i];
			}
		});
		jScrollPane1.setViewportView(jList1);

		javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
		jPanel9.setLayout(jPanel9Layout);
		jPanel9Layout.setHorizontalGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGap(0, 403, Short.MAX_VALUE));
		jPanel9Layout.setVerticalGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGap(0, 306, Short.MAX_VALUE));

		jPanel10.setBackground(new java.awt.Color(222, 222, 222));
		jPanel10.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Upcoming!",
				javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION,
				new java.awt.Font("Tahoma", 3, 14))); // NOI18N
		jPanel10.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

		javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
		jPanel10.setLayout(jPanel10Layout);
		jPanel10Layout.setHorizontalGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGap(0, 340, Short.MAX_VALUE));
		jPanel10Layout.setVerticalGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGap(0, 270, Short.MAX_VALUE));

		jPanel11.setBackground(new java.awt.Color(222, 222, 222));
		jPanel11.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Upcoming!",
				javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION,
				new java.awt.Font("Tahoma", 3, 14))); // NOI18N
		jPanel11.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

		javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
		jPanel11.setLayout(jPanel11Layout);
		jPanel11Layout.setHorizontalGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGap(0, 340, Short.MAX_VALUE));
		jPanel11Layout.setVerticalGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGap(0, 270, Short.MAX_VALUE));

		VenueNameLabel1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
		VenueNameLabel1.setForeground(new java.awt.Color(92, 64, 51));
		VenueNameLabel1.setText("Name");

		jTable1.setModel(
				new javax.swing.table.DefaultTableModel(
						new Object[][] { { null, null, null, null }, { null, null, null, null },
								{ null, null, null, null }, { null, null, null, null } },
						new String[] { "Title 1", "Title 2", "Title 3", "Title 4" }));
		jScrollPane2.setViewportView(jTable1);

		jTable2.setModel(
				new javax.swing.table.DefaultTableModel(
						new Object[][] { { null, null, null, null }, { null, null, null, null },
								{ null, null, null, null }, { null, null, null, null } },
						new String[] { "Title 1", "Title 2", "Title 3", "Title 4" }));
		jScrollPane3.setViewportView(jTable2);

		setBackground(new java.awt.Color(92, 64, 51));

		BackGroundPanel.setBackground(new java.awt.Color(92, 64, 51));

		OverviewTabbedPane.setBackground(new java.awt.Color(255, 222, 50));
		OverviewTabbedPane.setForeground(new java.awt.Color(92, 64, 51));
		OverviewTabbedPane.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N

		DashboardBackgroundPanel.setBackground(new java.awt.Color(255, 222, 50));

		DashboardWelcomeLabel.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
		DashboardWelcomeLabel.setForeground(new java.awt.Color(92, 64, 51));
		DashboardWelcomeLabel.setText("Welcome!");

		DashboardUpcomingPanel.setBackground(new java.awt.Color(92, 64, 51));
		DashboardUpcomingPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Upcoming!",
				javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION,
				new java.awt.Font("Tahoma", 3, 14), new java.awt.Color(255, 222, 89))); // NOI18N
		DashboardUpcomingPanel.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N

		UpcomingConcerts.setBackground(new java.awt.Color(255, 222, 50));
		UpcomingConcerts.setForeground(new java.awt.Color(92, 64, 51));
		UpcomingConcerts
				.setModel(new javax.swing.table.DefaultTableModel(
						new Object[][] { { null, null, null, null }, { null, null, null, null },
								{ null, null, null, null }, { null, null, null, null }, { null, null, null, null },
								{ null, null, null, null }, { null, null, null, null } },
						new String[] { "Title 1", "Title 2", "Title 3", "Title 4" }));
		jScrollPane4.setViewportView(UpcomingConcerts);

		javax.swing.GroupLayout DashboardUpcomingPanelLayout = new javax.swing.GroupLayout(DashboardUpcomingPanel);
		DashboardUpcomingPanel.setLayout(DashboardUpcomingPanelLayout);
		DashboardUpcomingPanelLayout.setHorizontalGroup(DashboardUpcomingPanelLayout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGap(0, 908, Short.MAX_VALUE)
				.addGroup(DashboardUpcomingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(DashboardUpcomingPanelLayout.createSequentialGroup().addContainerGap()
								.addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 896, Short.MAX_VALUE)
								.addContainerGap())));
		DashboardUpcomingPanelLayout.setVerticalGroup(DashboardUpcomingPanelLayout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGap(0, 256, Short.MAX_VALUE)
				.addGroup(DashboardUpcomingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
								DashboardUpcomingPanelLayout.createSequentialGroup()
										.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
										.addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 237,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addContainerGap(13, Short.MAX_VALUE))));

		DashboardRefreshButton.setBackground(new java.awt.Color(92, 64, 51));
		DashboardRefreshButton.setForeground(new java.awt.Color(255, 222, 89));
		DashboardRefreshButton.setText("Refresh");
		DashboardRefreshButton.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				DashboardRefreshButtonActionPerformed(evt);
			}
		});

		javax.swing.GroupLayout DashboardBackgroundPanelLayout = new javax.swing.GroupLayout(DashboardBackgroundPanel);
		DashboardBackgroundPanel.setLayout(DashboardBackgroundPanelLayout);
		DashboardBackgroundPanelLayout.setHorizontalGroup(
				DashboardBackgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(DashboardBackgroundPanelLayout.createSequentialGroup().addGap(6, 6, 6)
								.addComponent(DashboardWelcomeLabel)
								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED,
										javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
								.addComponent(DashboardRefreshButton).addContainerGap())
						.addGroup(DashboardBackgroundPanelLayout.createSequentialGroup()
								.addComponent(DashboardUpcomingPanel, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addGap(0, 0, Short.MAX_VALUE)));
		DashboardBackgroundPanelLayout.setVerticalGroup(DashboardBackgroundPanelLayout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(DashboardBackgroundPanelLayout.createSequentialGroup().addGap(6, 6, 6)
						.addGroup(DashboardBackgroundPanelLayout
								.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(DashboardWelcomeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 58,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(DashboardRefreshButton))
						.addGap(6, 6, 6).addComponent(DashboardUpcomingPanel, javax.swing.GroupLayout.PREFERRED_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)));

		OverviewTabbedPane.addTab("Dashboard", DashboardBackgroundPanel);

		jPanel2.setBackground(new java.awt.Color(92, 64, 51));

		CreationCenterTabsTabbedPane.setBackground(new java.awt.Color(255, 222, 50));
		CreationCenterTabsTabbedPane.setForeground(new java.awt.Color(92, 64, 51));
		CreationCenterTabsTabbedPane.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N

		VenueBackgroundPanel.setBackground(new java.awt.Color(255, 222, 50));

		VenueBackgroundPanel2.setBackground(new java.awt.Color(255, 222, 50));

		HeaderVenue.setBackground(new java.awt.Color(255, 222, 89));
		HeaderVenue.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
		HeaderVenue.setForeground(new java.awt.Color(92, 64, 51));
		HeaderVenue.setText("Please Enter the Information Below");

		numberofSectionsLabel.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
		numberofSectionsLabel.setForeground(new java.awt.Color(92, 64, 51));
		numberofSectionsLabel.setText("# of Sections");

		VenueIDTextfield.setBackground(new java.awt.Color(92, 64, 51));
		VenueIDTextfield.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
		VenueIDTextfield.setForeground(new java.awt.Color(255, 222, 89));
		VenueIDTextfield.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

		SeatsperSectionTextfield.setBackground(new java.awt.Color(92, 64, 51));
		SeatsperSectionTextfield.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
		SeatsperSectionTextfield.setForeground(new java.awt.Color(255, 222, 89));
		SeatsperSectionTextfield
				.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
		SeatsperSectionTextfield.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				SeatsperSectionTextfieldActionPerformed(evt);
			}
		});

		VenueCreateButton.setBackground(new java.awt.Color(92, 64, 51));
		VenueCreateButton.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
		VenueCreateButton.setForeground(new java.awt.Color(255, 222, 89));
		VenueCreateButton.setText("Create!");
		VenueCreateButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
		VenueCreateButton.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				VenueCreateButtonActionPerformed(evt);
			}
		});

		VenueAddressLabel.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
		VenueAddressLabel.setForeground(new java.awt.Color(92, 64, 51));
		VenueAddressLabel.setText("Address");

		VenueIDLabel.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
		VenueIDLabel.setForeground(new java.awt.Color(92, 64, 51));
		VenueIDLabel.setText("Venue ID");

		numberofSeatsLabel.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
		numberofSeatsLabel.setForeground(new java.awt.Color(92, 64, 51));
		numberofSeatsLabel.setText("# of Seats Per Section");

		numberofSectionsTextfield.setBackground(new java.awt.Color(92, 64, 51));
		numberofSectionsTextfield.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
		numberofSectionsTextfield.setForeground(new java.awt.Color(255, 222, 89));
		numberofSectionsTextfield
				.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
		numberofSectionsTextfield.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				numberofSectionsTextfieldActionPerformed(evt);
			}
		});

		VenueAddressTextfield.setBackground(new java.awt.Color(92, 64, 51));
		VenueAddressTextfield.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
		VenueAddressTextfield.setForeground(new java.awt.Color(255, 222, 89));
		VenueAddressTextfield
				.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
		VenueAddressTextfield.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				VenueAddressTextfieldActionPerformed(evt);
			}
		});

		VenueNameLabel.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
		VenueNameLabel.setForeground(new java.awt.Color(92, 64, 51));
		VenueNameLabel.setText("Name");

		VenueNameTextfield.setBackground(new java.awt.Color(92, 64, 51));
		VenueNameTextfield.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
		VenueNameTextfield.setForeground(new java.awt.Color(255, 222, 89));
		VenueNameTextfield
				.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
		VenueNameTextfield.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				VenueNameTextfieldActionPerformed(evt);
			}
		});

		btnGen = new JButton("Generate ID");
		btnGen.setFont(new Font("Times New Roman", Font.PLAIN, 10));
		btnGen.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent e) {

				Random rand = new Random();
				boolean generating = true;
				VenueHandler vh = new VenueHandler();
				int genNum;

				while (generating) {

					genNum = rand.nextInt(100000);

					if (vh.searchForVenue(genNum) == false) {
						VenueIDTextfield.setText("" + genNum);
						generating = false;
					}

				}

			}
		});
		btnGen.setBackground(new Color(92, 64, 51));
		btnGen.setForeground(new Color(255, 222, 50));

		javax.swing.GroupLayout VenueBackgroundPanel2Layout = new javax.swing.GroupLayout(VenueBackgroundPanel2);
		VenueBackgroundPanel2Layout.setHorizontalGroup(VenueBackgroundPanel2Layout
				.createParallelGroup(Alignment.LEADING)
				.addGroup(VenueBackgroundPanel2Layout.createSequentialGroup().addComponent(HeaderVenue).addGap(0, 519,
						Short.MAX_VALUE))
				.addGroup(VenueBackgroundPanel2Layout.createSequentialGroup().addGroup(VenueBackgroundPanel2Layout
						.createParallelGroup(Alignment.LEADING)
						.addGroup(VenueBackgroundPanel2Layout.createSequentialGroup().addContainerGap()
								.addGroup(VenueBackgroundPanel2Layout.createParallelGroup(Alignment.LEADING)
										.addGroup(VenueBackgroundPanel2Layout.createSequentialGroup()
												.addGap(0, 674, Short.MAX_VALUE).addComponent(VenueCreateButton,
														GroupLayout.PREFERRED_SIZE, 89, GroupLayout.PREFERRED_SIZE))
										.addGroup(VenueBackgroundPanel2Layout.createSequentialGroup()
												.addGroup(VenueBackgroundPanel2Layout
														.createParallelGroup(Alignment.LEADING)
														.addComponent(numberofSeatsLabel)
														.addComponent(numberofSectionsLabel, Alignment.TRAILING)
														.addComponent(VenueAddressLabel, Alignment.TRAILING,
																GroupLayout.PREFERRED_SIZE, 66,
																GroupLayout.PREFERRED_SIZE))
												.addGap(18)
												.addGroup(VenueBackgroundPanel2Layout
														.createParallelGroup(Alignment.TRAILING)
														.addComponent(SeatsperSectionTextfield,
																GroupLayout.PREFERRED_SIZE, 380,
																GroupLayout.PREFERRED_SIZE)
														.addComponent(numberofSectionsTextfield,
																GroupLayout.PREFERRED_SIZE, 380,
																GroupLayout.PREFERRED_SIZE))
												.addGap(0, 202, Short.MAX_VALUE))))
						.addGroup(VenueBackgroundPanel2Layout.createSequentialGroup().addGap(110)
								.addGroup(VenueBackgroundPanel2Layout.createParallelGroup(Alignment.TRAILING)
										.addComponent(VenueNameLabel, GroupLayout.PREFERRED_SIZE, 49,
												GroupLayout.PREFERRED_SIZE)
										.addComponent(VenueIDLabel))
								.addPreferredGap(ComponentPlacement.RELATED)
								.addGroup(VenueBackgroundPanel2Layout.createParallelGroup(Alignment.LEADING)
										.addGroup(VenueBackgroundPanel2Layout.createSequentialGroup()
												.addComponent(VenueIDTextfield, GroupLayout.PREFERRED_SIZE, 380,
														GroupLayout.PREFERRED_SIZE)
												.addPreferredGap(ComponentPlacement.UNRELATED).addComponent(btnGen))
										.addComponent(VenueNameTextfield, GroupLayout.PREFERRED_SIZE, 380,
												GroupLayout.PREFERRED_SIZE)
										.addComponent(VenueAddressTextfield, GroupLayout.PREFERRED_SIZE, 380,
												GroupLayout.PREFERRED_SIZE))))
						.addContainerGap()));
		VenueBackgroundPanel2Layout.setVerticalGroup(VenueBackgroundPanel2Layout.createParallelGroup(Alignment.LEADING)
				.addGroup(VenueBackgroundPanel2Layout.createSequentialGroup().addGap(12)
						.addComponent(HeaderVenue, GroupLayout.PREFERRED_SIZE, 28, GroupLayout.PREFERRED_SIZE)
						.addGap(27)
						.addGroup(VenueBackgroundPanel2Layout.createParallelGroup(Alignment.BASELINE)
								.addComponent(VenueIDLabel)
								.addComponent(VenueIDTextfield, GroupLayout.PREFERRED_SIZE, 21,
										GroupLayout.PREFERRED_SIZE)
								.addComponent(btnGen))
						.addPreferredGap(ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
						.addGroup(VenueBackgroundPanel2Layout.createParallelGroup(Alignment.BASELINE)
								.addComponent(VenueNameLabel).addComponent(VenueNameTextfield,
										GroupLayout.PREFERRED_SIZE, 21, GroupLayout.PREFERRED_SIZE))
						.addPreferredGap(ComponentPlacement.RELATED)
						.addGroup(VenueBackgroundPanel2Layout.createParallelGroup(Alignment.BASELINE)
								.addComponent(VenueAddressLabel).addComponent(VenueAddressTextfield,
										GroupLayout.PREFERRED_SIZE, 21, GroupLayout.PREFERRED_SIZE))
						.addPreferredGap(ComponentPlacement.UNRELATED)
						.addGroup(VenueBackgroundPanel2Layout.createParallelGroup(Alignment.LEADING)
								.addComponent(numberofSectionsLabel, Alignment.TRAILING)
								.addComponent(numberofSectionsTextfield, Alignment.TRAILING, GroupLayout.PREFERRED_SIZE,
										21, GroupLayout.PREFERRED_SIZE))
						.addGap(18)
						.addGroup(VenueBackgroundPanel2Layout.createParallelGroup(Alignment.BASELINE)
								.addComponent(SeatsperSectionTextfield, GroupLayout.PREFERRED_SIZE, 21,
										GroupLayout.PREFERRED_SIZE)
								.addComponent(numberofSeatsLabel))
						.addGap(53)
						.addComponent(VenueCreateButton, GroupLayout.PREFERRED_SIZE, 31, GroupLayout.PREFERRED_SIZE)
						.addContainerGap()));
		VenueBackgroundPanel2.setLayout(VenueBackgroundPanel2Layout);

		javax.swing.GroupLayout VenueBackgroundPanelLayout = new javax.swing.GroupLayout(VenueBackgroundPanel);
		VenueBackgroundPanel.setLayout(VenueBackgroundPanelLayout);
		VenueBackgroundPanelLayout.setHorizontalGroup(
				VenueBackgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(VenueBackgroundPanelLayout.createSequentialGroup().addGap(16, 16, 16)
								.addComponent(VenueBackgroundPanel2, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addContainerGap(125, Short.MAX_VALUE)));
		VenueBackgroundPanelLayout.setVerticalGroup(
				VenueBackgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(VenueBackgroundPanelLayout.createSequentialGroup()
								.addComponent(VenueBackgroundPanel2, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addContainerGap(18, Short.MAX_VALUE)));

		CreationCenterTabsTabbedPane.addTab("Venue", VenueBackgroundPanel);

		ConcertBackgroundPanel.setBackground(new java.awt.Color(255, 222, 50));

		HeaderConcert.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
		HeaderConcert.setForeground(new java.awt.Color(92, 64, 51));
		HeaderConcert.setText("Please Enter the Information Below");

		ConcertCreateButton.setBackground(new java.awt.Color(92, 64, 51));
		ConcertCreateButton.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
		ConcertCreateButton.setForeground(new java.awt.Color(255, 222, 89));
		ConcertCreateButton.setText("Create!");
		ConcertCreateButton
				.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
		ConcertCreateButton.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				ConcertCreateButtonActionPerformed(evt);
			}
		});

		ConcertNameLabel.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
		ConcertNameLabel.setForeground(new java.awt.Color(92, 64, 51));
		ConcertNameLabel.setText("Name");

		ConcertNameTextfield.setBackground(new java.awt.Color(92, 64, 51));
		ConcertNameTextfield.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
		ConcertNameTextfield.setForeground(new java.awt.Color(255, 222, 89));
		ConcertNameTextfield
				.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

		jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
		jLabel3.setForeground(new java.awt.Color(92, 64, 51));
		jLabel3.setText("Date");

		jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
		jLabel4.setForeground(new java.awt.Color(92, 64, 51));
		jLabel4.setText("Price");

		ConcertVenueLabel.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
		ConcertVenueLabel.setForeground(new java.awt.Color(92, 64, 51));
		ConcertVenueLabel.setText("Venue");

		ConcertArtistLabel.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
		ConcertArtistLabel.setForeground(new java.awt.Color(92, 64, 51));
		ConcertArtistLabel.setText("Artist");

		VenueSelectionComboBox.setBackground(new java.awt.Color(92, 64, 51));
		VenueSelectionComboBox.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
		VenueSelectionComboBox.setForeground(new java.awt.Color(255, 222, 89));
		VenueSelectionComboBox.setModel(
				new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
		VenueSelectionComboBox
				.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

		ArtistSelectionComboBox.setBackground(new java.awt.Color(92, 64, 51));
		ArtistSelectionComboBox.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
		ArtistSelectionComboBox.setForeground(new java.awt.Color(255, 222, 89));
		ArtistSelectionComboBox.setModel(
				new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
		ArtistSelectionComboBox
				.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

		ConcertPriceTextfield.setBackground(new java.awt.Color(92, 64, 51));
		ConcertPriceTextfield.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
		ConcertPriceTextfield.setForeground(new java.awt.Color(255, 222, 89));
		ConcertPriceTextfield
				.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

		ConcertDateTextfield.setBackground(new java.awt.Color(92, 64, 51));
		ConcertDateTextfield.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
		ConcertDateTextfield.setForeground(new java.awt.Color(255, 222, 89));
		ConcertDateTextfield
				.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

		CreationRefreshButton.setBackground(new java.awt.Color(92, 64, 51));
		CreationRefreshButton.setForeground(new java.awt.Color(255, 222, 89));
		CreationRefreshButton.setText("Refresh");
		CreationRefreshButton.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				CreationRefreshButtonActionPerformed(evt);
			}
		});

		javax.swing.GroupLayout ConcertBackgroundPanelLayout = new javax.swing.GroupLayout(ConcertBackgroundPanel);
		ConcertBackgroundPanel.setLayout(ConcertBackgroundPanelLayout);
		ConcertBackgroundPanelLayout.setHorizontalGroup(ConcertBackgroundPanelLayout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(ConcertBackgroundPanelLayout.createSequentialGroup().addContainerGap()
						.addGroup(ConcertBackgroundPanelLayout
								.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addGroup(ConcertBackgroundPanelLayout.createSequentialGroup()
										.addGroup(ConcertBackgroundPanelLayout
												.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
												.addComponent(ConcertNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE,
														49, javax.swing.GroupLayout.PREFERRED_SIZE)
												.addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 49,
														javax.swing.GroupLayout.PREFERRED_SIZE))
										.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addGroup(ConcertBackgroundPanelLayout
												.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
												.addComponent(ConcertNameTextfield,
														javax.swing.GroupLayout.DEFAULT_SIZE, 218, Short.MAX_VALUE)
												.addComponent(ConcertDateTextfield))
										.addGap(18, 18, 18).addComponent(ConcertVenueLabel)
										.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(VenueSelectionComboBox, javax.swing.GroupLayout.PREFERRED_SIZE,
												162, javax.swing.GroupLayout.PREFERRED_SIZE)
										.addGap(18, 18, 18)
										.addComponent(ConcertArtistLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 62,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(ArtistSelectionComboBox, javax.swing.GroupLayout.PREFERRED_SIZE,
												177, javax.swing.GroupLayout.PREFERRED_SIZE)
										.addGap(0, 144, Short.MAX_VALUE))
								.addGroup(ConcertBackgroundPanelLayout.createSequentialGroup()
										.addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 49,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(ConcertPriceTextfield, javax.swing.GroupLayout.PREFERRED_SIZE,
												218, javax.swing.GroupLayout.PREFERRED_SIZE)
										.addContainerGap(639, Short.MAX_VALUE))
								.addGroup(
										ConcertBackgroundPanelLayout.createSequentialGroup().addComponent(HeaderConcert)
												.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED,
														javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
												.addComponent(CreationRefreshButton).addGap(37, 37, 37))))
				.addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
						ConcertBackgroundPanelLayout.createSequentialGroup()
								.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
								.addComponent(ConcertCreateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 79,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addGap(18, 18, 18)));
		ConcertBackgroundPanelLayout.setVerticalGroup(ConcertBackgroundPanelLayout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(ConcertBackgroundPanelLayout.createSequentialGroup().addGap(12, 12, 12)
						.addGroup(ConcertBackgroundPanelLayout
								.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(HeaderConcert, javax.swing.GroupLayout.PREFERRED_SIZE, 28,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(CreationRefreshButton))
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
						.addGroup(ConcertBackgroundPanelLayout
								.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addComponent(ConcertNameTextfield, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addGroup(ConcertBackgroundPanelLayout
										.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
										.addComponent(ConcertArtistLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addComponent(ConcertVenueLabel)
										.addComponent(VenueSelectionComboBox, javax.swing.GroupLayout.PREFERRED_SIZE,
												22, javax.swing.GroupLayout.PREFERRED_SIZE)
										.addComponent(ArtistSelectionComboBox, javax.swing.GroupLayout.PREFERRED_SIZE,
												22, javax.swing.GroupLayout.PREFERRED_SIZE)
										.addComponent(ConcertNameLabel)))
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addGroup(ConcertBackgroundPanelLayout
								.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(ConcertDateTextfield, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(jLabel3))
						.addGap(10, 10, 10)
						.addGroup(ConcertBackgroundPanelLayout
								.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE).addComponent(jLabel4)
								.addComponent(ConcertPriceTextfield, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 152, Short.MAX_VALUE)
						.addComponent(ConcertCreateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addContainerGap()));

		CreationCenterTabsTabbedPane.addTab("Concert", ConcertBackgroundPanel);

		javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
		jPanel2.setLayout(jPanel2Layout);
		jPanel2Layout.setHorizontalGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addComponent(CreationCenterTabsTabbedPane));
		jPanel2Layout.setVerticalGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addComponent(CreationCenterTabsTabbedPane, javax.swing.GroupLayout.Alignment.TRAILING));

		OverviewTabbedPane.addTab("Creation Center", jPanel2);

		javax.swing.GroupLayout BackGroundPanelLayout = new javax.swing.GroupLayout(BackGroundPanel);
		BackGroundPanel.setLayout(BackGroundPanelLayout);
		BackGroundPanelLayout.setHorizontalGroup(BackGroundPanelLayout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(OverviewTabbedPane));
		BackGroundPanelLayout.setVerticalGroup(
				BackGroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(
						javax.swing.GroupLayout.Alignment.TRAILING,
						BackGroundPanelLayout.createSequentialGroup().addGap(0, 0, Short.MAX_VALUE).addComponent(
								OverviewTabbedPane, javax.swing.GroupLayout.PREFERRED_SIZE, 405,
								javax.swing.GroupLayout.PREFERRED_SIZE)));

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(layout.createSequentialGroup()
						.addComponent(BackGroundPanel, javax.swing.GroupLayout.PREFERRED_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addGap(0, 0, 0)));
		layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(
				javax.swing.GroupLayout.Alignment.TRAILING,
				layout.createSequentialGroup().addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
						.addComponent(BackGroundPanel, javax.swing.GroupLayout.PREFERRED_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addGap(0, 0, 0)));

		pack();
	}// </editor-fold>//GEN-END:initComponents

	private void ConcertCreateButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_ConcertCreateButtonActionPerformed
		
		try {
			String name = ConcertNameTextfield.getText();
			String date = ConcertDateTextfield.getText();
			float price = Float.parseFloat(ConcertPriceTextfield.getText());
			Venue c = (Venue) VenueSelectionComboBox.getSelectedItem();
			int vId = c.getvId();
			Artist a = (Artist) ArtistSelectionComboBox.getSelectedItem();
			int artistId = a.getartistId();

			new ConcertHandler().addConcert(name, date, price, vId, artistId);

			ConcertNameTextfield.setText(null);
			ConcertDateTextfield.setText(null);
			ConcertPriceTextfield.setText(null);
		}
		catch (NumberFormatException e) {
			JOptionPane.showMessageDialog(this, "Price is invalid");
		}
	}// GEN-LAST:event_ConcertCreateButtonActionPerformed

	private void VenueCreateButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_VenueCreateButtonActionPerformed
		
		try {
			int vId = Integer.parseInt(VenueIDTextfield.getText());
			
			if (new VenueHandler().searchForVenue(vId)) {
				JOptionPane.showMessageDialog(this, "ERROR: Venue ID is already taken.");
			}
			else {
				String vName = VenueIDTextfield.getText();
				String address = VenueAddressTextfield.getText();
			
				SectionHandler secH = new SectionHandler();
				SeatHandler seatH = new SeatHandler();

				new VenueHandler().addVenue(vId, address, vName);

				int sectionTotal = Integer.parseInt(numberofSectionsTextfield.getText());

				int seatTotal = Integer.parseInt(SeatsperSectionTextfield.getText());
				for (int sectionNo = 1; sectionNo <= sectionTotal; sectionNo++) {
					secH.addSection(sectionNo, vId);
					for (int seatNo = 1; seatNo <= seatTotal; seatNo++) {
						seatH.addSeat(seatNo, sectionNo, vId);
					}

				}

				VenueIDTextfield.setText(null);
				VenueNameTextfield.setText(null);
				VenueAddressTextfield.setText(null);
				numberofSectionsTextfield.setText(null);
				SeatsperSectionTextfield.setText(null);
			}
			
		}
		catch (NumberFormatException e) {
			JOptionPane.showMessageDialog(this, "Number formatting is invalid");
		}
		
	}// GEN-LAST:event_VenueCreateButtonActionPerformed

	private void VenueAddressTextfieldActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_VenueAddressTextfieldActionPerformed
		// TODO add your handling code here:
	}// GEN-LAST:event_VenueAddressTextfieldActionPerformed

	private void numberofSectionsTextfieldActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_numberofSectionsTextfieldActionPerformed
		
	}// GEN-LAST:event_numberofSectionsTextfieldActionPerformed

	private void DashboardRefreshButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_DashboardRefreshButtonActionPerformed
		populateConcert();
	}// GEN-LAST:event_DashboardRefreshButtonActionPerformed

	private void CreationRefreshButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_CreationRefreshButtonActionPerformed
		populateVenue();
		populateArtist(); // TODO add your handling code here:
	}// GEN-LAST:event_CreationRefreshButtonActionPerformed

	private void SeatsperSectionTextfieldActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_SeatsperSectionTextfieldActionPerformed
		// TODO add your handling code here:
	}// GEN-LAST:event_SeatsperSectionTextfieldActionPerformed

	private void VenueNameTextfieldActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_VenueNameTextfieldActionPerformed
		// TODO add your handling code here:
	}// GEN-LAST:event_VenueNameTextfieldActionPerformed

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JComboBox<String> ArtistSelectionComboBox;
	private javax.swing.JPanel BackGroundPanel;
	private javax.swing.JLabel ConcertArtistLabel;
	private javax.swing.JPanel ConcertBackgroundPanel;
	private javax.swing.JButton ConcertCreateButton;
	private javax.swing.JTextField ConcertDateTextfield;
	private javax.swing.JLabel ConcertNameLabel;
	private javax.swing.JTextField ConcertNameTextfield;
	private javax.swing.JTextField ConcertPriceTextfield;
	private javax.swing.JLabel ConcertVenueLabel;
	private javax.swing.JTabbedPane CreationCenterTabsTabbedPane;
	private javax.swing.JButton CreationRefreshButton;
	private javax.swing.JPanel DashboardBackgroundPanel;
	private javax.swing.JButton DashboardRefreshButton;
	private javax.swing.JPanel DashboardUpcomingPanel;
	private javax.swing.JLabel DashboardWelcomeLabel;
	private javax.swing.JLabel HeaderConcert;
	private javax.swing.JLabel HeaderVenue;
	private javax.swing.JTabbedPane OverviewTabbedPane;
	private javax.swing.JTextField SeatsperSectionTextfield;
	private javax.swing.JTable UpcomingConcerts;
	private javax.swing.JLabel VenueAddressLabel;
	private javax.swing.JTextField VenueAddressTextfield;
	private javax.swing.JPanel VenueBackgroundPanel;
	private javax.swing.JPanel VenueBackgroundPanel2;
	private javax.swing.JButton VenueCreateButton;
	private javax.swing.JLabel VenueIDLabel;
	private javax.swing.JTextField VenueIDTextfield;
	private javax.swing.JLabel VenueNameLabel;
	private javax.swing.JLabel VenueNameLabel1;
	private javax.swing.JTextField VenueNameTextfield;
	private javax.swing.JComboBox<String> VenueSelectionComboBox;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JLabel jLabel4;
	private javax.swing.JList<String> jList1;
	private javax.swing.JPanel jPanel10;
	private javax.swing.JPanel jPanel11;
	private javax.swing.JPanel jPanel2;
	private javax.swing.JPanel jPanel9;
	private javax.swing.JScrollPane jScrollPane1;
	private javax.swing.JScrollPane jScrollPane2;
	private javax.swing.JScrollPane jScrollPane3;
	private javax.swing.JScrollPane jScrollPane4;
	private javax.swing.JTable jTable1;
	private javax.swing.JTable jTable2;
	private javax.swing.JLabel numberofSeatsLabel;
	private javax.swing.JLabel numberofSectionsLabel;
	private javax.swing.JTextField numberofSectionsTextfield;
	private JButton btnGen;
}
