/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package concertdb;

import java.util.List;

import javax.swing.table.DefaultTableModel;

import bo.Concert2;
import bo.User;
import dao.ConcertHandler;
import dao.UserHandler;
import javax.swing.GroupLayout.Alignment;
import javax.swing.GroupLayout;
import javax.swing.JButton;
import javax.swing.LayoutStyle.ComponentPlacement;
import java.awt.Color;
import java.awt.event.ActionListener;
import java.awt.event.ActionEvent;

/**
 *
 * @author Kohner Smith & Logan Alpha
 */
public class UserMainPage2 extends BaseWindow {
	
	private UserHandler uh = new UserHandler();
	private User u;
	
    /**
     * Creates new form UserMainPage2
     */
    public UserMainPage2(BaseWindow lw, User u) {
    	
    	this.u = u;
    	this.lastWindow = lw;
    	closePrevious();
    	
    	try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UserMainPage2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UserMainPage2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UserMainPage2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserMainPage2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        this.lastWindow = lw;
        initComponents();
        populateConcert2();
        populateConcert3();
        this.setTitle("Main Page");
        this.setVisible(true);
    }
    List<Concert2> concerts;
    private void populateConcert2(){
        String keyword = SearchTextfield.getText();
        concerts = new ConcertHandler().getConcerts2(keyword);
        String columns[] = new String[]{"Name", "Date", "Price", "Venue", "Artist"};
        DefaultTableModel tblModel = new DefaultTableModel(columns, 0){
                @Override
            public boolean isCellEditable(int row, int column) {
                return false; 
            }
            
        };
        concerts.forEach((name)->{
           tblModel.addRow(name.getRow()); 
        });
        ConcertList.setModel(tblModel);
    }
    
    List<Concert2> booked;
    private void populateConcert3(){
    	
        booked = new ConcertHandler().getConcerts3(u);
        String columns[] = new String[]{"Name", "Date", "Ticket No.", "Venue"};
        DefaultTableModel tblModel = new DefaultTableModel(columns, 0){
                @Override
            public boolean isCellEditable(int row, int column) {
                return false; 
            }
            
        };
        booked.forEach((name)->{
           tblModel.addRow(name.getRow()); 
        });
        BookedList.setModel(tblModel);
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BackgroundPanel = new javax.swing.JPanel();
        TabbedPaneGroup = new javax.swing.JTabbedPane();
        AccountPanel = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        BookedPanel = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        BookedList = new javax.swing.JTable();
        AboutPanel = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        ConcertListPanel = new javax.swing.JPanel();
        UpComingConcertsLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ConcertList = new javax.swing.JTable();
        SearchTextfield = new javax.swing.JTextField();
        SearchButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        BackgroundPanel.setBackground(new java.awt.Color(92, 64, 51));

        TabbedPaneGroup.setBackground(new java.awt.Color(255, 222, 50));
        TabbedPaneGroup.setForeground(new java.awt.Color(92, 64, 51));
        TabbedPaneGroup.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N

        AccountPanel.setBackground(new java.awt.Color(255, 222, 50));

        jPanel1.setBackground(new java.awt.Color(92, 64, 51));

        jLabel1.setForeground(new java.awt.Color(255, 222, 50));
        jLabel1.setText("Account ID:");

        jLabel2.setForeground(new java.awt.Color(255, 222, 50));
        jLabel2.setText("Email: ");

        jLabel3.setForeground(new java.awt.Color(255, 222, 50));
        jLabel3.setText("Name: ");

        jLabel4.setForeground(new java.awt.Color(255, 222, 50));
        jLabel4.setText("" + uh.getID2(u.getUserEmail()));

        jLabel5.setForeground(new java.awt.Color(255, 222, 50));
        jLabel5.setText(u.getUserEmail());

        jLabel6.setForeground(new java.awt.Color(255, 222, 50));
        jLabel6.setText(u.getUserName());

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(113, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addGap(41, 41, 41)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addGap(49, 49, 49)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addContainerGap(122, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout AccountPanelLayout = new javax.swing.GroupLayout(AccountPanel);
        AccountPanel.setLayout(AccountPanelLayout);
        AccountPanelLayout.setHorizontalGroup(
            AccountPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AccountPanelLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(26, Short.MAX_VALUE))
        );
        AccountPanelLayout.setVerticalGroup(
            AccountPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AccountPanelLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(44, Short.MAX_VALUE))
        );

        TabbedPaneGroup.addTab("Account", AccountPanel);

        BookedPanel.setBackground(new java.awt.Color(255, 222, 50));

        jScrollPane3.setBackground(new java.awt.Color(92, 64, 51));
        jScrollPane3.setForeground(new java.awt.Color(255, 222, 50));

        BookedList.setBackground(new java.awt.Color(92, 64, 51));
        BookedList.setForeground(new java.awt.Color(255, 222, 50));
        BookedList.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(BookedList);
        
        JButton btnNewButton = new JButton("Refresh");
        btnNewButton.addActionListener(new ActionListener() {
        	public void actionPerformed(ActionEvent e) {
        		populateConcert3();
        	}
        });
        btnNewButton.setForeground(new Color(92, 64, 51));
        btnNewButton.setBackground(new Color(255, 222, 89));

        javax.swing.GroupLayout BookedPanelLayout = new javax.swing.GroupLayout(BookedPanel);
        BookedPanelLayout.setHorizontalGroup(
        	BookedPanelLayout.createParallelGroup(Alignment.LEADING)
        		.addGroup(BookedPanelLayout.createSequentialGroup()
        			.addGap(88)
        			.addComponent(btnNewButton)
        			.addContainerGap())
        		.addGroup(BookedPanelLayout.createSequentialGroup()
        			.addGap(14)
        			.addComponent(jScrollPane3, GroupLayout.DEFAULT_SIZE, 232, Short.MAX_VALUE)
        			.addGap(14))
        );
        BookedPanelLayout.setVerticalGroup(
        	BookedPanelLayout.createParallelGroup(Alignment.LEADING)
        		.addGroup(BookedPanelLayout.createSequentialGroup()
        			.addGap(16)
        			.addComponent(btnNewButton)
        			.addGap(10)
        			.addComponent(jScrollPane3, GroupLayout.PREFERRED_SIZE, 404, GroupLayout.PREFERRED_SIZE)
        			.addContainerGap(53, Short.MAX_VALUE))
        );
        BookedPanel.setLayout(BookedPanelLayout);

        TabbedPaneGroup.addTab("Booked", BookedPanel);

        AboutPanel.setBackground(new java.awt.Color(255, 222, 50));

        jTextArea1.setBackground(new java.awt.Color(92, 64, 51));
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jTextArea1.setForeground(new java.awt.Color(255, 222, 50));
        jTextArea1.setLineWrap(true);
        jTextArea1.setRows(5);
        jTextArea1.setText("Hello and welcome to \nEvent Hub! \n\nWe are so excited to have \nyou be apart of our \ncommunity!\n\nAt EventHub we strive to\nconnect consumers with\nthe most up to date \nconcert information. \n\nIf you have any questions\nplease reach out \n\nHappy Concerting!");
        jScrollPane2.setViewportView(jTextArea1);

        javax.swing.GroupLayout AboutPanelLayout = new javax.swing.GroupLayout(AboutPanel);
        AboutPanel.setLayout(AboutPanelLayout);
        AboutPanelLayout.setHorizontalGroup(
            AboutPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AboutPanelLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );
        AboutPanelLayout.setVerticalGroup(
            AboutPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AboutPanelLayout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 417, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(44, Short.MAX_VALUE))
        );

        TabbedPaneGroup.addTab("About", AboutPanel);

        ConcertListPanel.setBackground(new java.awt.Color(255, 222, 50));

        UpComingConcertsLabel.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        UpComingConcertsLabel.setForeground(new java.awt.Color(92, 64, 51));
        UpComingConcertsLabel.setText("Up Coming Concerts!");

        ConcertList.setBackground(new java.awt.Color(92, 64, 51));
        ConcertList.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        ConcertList.setForeground(new java.awt.Color(255, 222, 50));
        ConcertList.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        ConcertList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ConcertListMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(ConcertList);

        SearchTextfield.setBackground(new java.awt.Color(92, 64, 51));
        SearchTextfield.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        SearchTextfield.setForeground(new java.awt.Color(255, 222, 50));

        SearchButton.setBackground(new java.awt.Color(92, 64, 51));
        SearchButton.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        SearchButton.setForeground(new java.awt.Color(255, 222, 50));
        SearchButton.setText("Search");
        SearchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ConcertListPanelLayout = new javax.swing.GroupLayout(ConcertListPanel);
        ConcertListPanel.setLayout(ConcertListPanelLayout);
        ConcertListPanelLayout.setHorizontalGroup(
            ConcertListPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ConcertListPanelLayout.createSequentialGroup()
                .addContainerGap(45, Short.MAX_VALUE)
                .addGroup(ConcertListPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ConcertListPanelLayout.createSequentialGroup()
                        .addComponent(SearchTextfield)
                        .addGap(18, 18, 18)
                        .addComponent(SearchButton)))
                .addGap(31, 31, 31))
            .addGroup(ConcertListPanelLayout.createSequentialGroup()
                .addGap(122, 122, 122)
                .addComponent(UpComingConcertsLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        ConcertListPanelLayout.setVerticalGroup(
            ConcertListPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ConcertListPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(UpComingConcertsLabel)
                .addGap(43, 43, 43)
                .addGroup(ConcertListPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SearchTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SearchButton))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 347, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35))
        );

        javax.swing.GroupLayout BackgroundPanelLayout = new javax.swing.GroupLayout(BackgroundPanel);
        BackgroundPanel.setLayout(BackgroundPanelLayout);
        BackgroundPanelLayout.setHorizontalGroup(
            BackgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BackgroundPanelLayout.createSequentialGroup()
                .addComponent(TabbedPaneGroup, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ConcertListPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        BackgroundPanelLayout.setVerticalGroup(
            BackgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(TabbedPaneGroup)
            .addComponent(ConcertListPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BackgroundPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 788, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BackgroundPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SearchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchButtonActionPerformed
        populateConcert2();        // TODO add your handling code here:
    }//GEN-LAST:event_SearchButtonActionPerformed

    private void ConcertListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ConcertListMouseClicked
        if (evt.getClickCount() == 2){
           Concert2 selectedConcert = concerts.get(ConcertList.getSelectedRow()); 
            PaymentPage paymentpage = new PaymentPage(selectedConcert, u);
            paymentpage.setVisible(true);
        }
    }//GEN-LAST:event_ConcertListMouseClicked



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel AboutPanel;
    private javax.swing.JPanel AccountPanel;
    private javax.swing.JPanel BackgroundPanel;
    private javax.swing.JPanel BookedPanel;
    private javax.swing.JTable ConcertList;
    private javax.swing.JPanel ConcertListPanel;
    private javax.swing.JButton SearchButton;
    private javax.swing.JTextField SearchTextfield;
    private javax.swing.JTabbedPane TabbedPaneGroup;
    private javax.swing.JLabel UpComingConcertsLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable BookedList;
    private javax.swing.JTextArea jTextArea1;
}
